### PR TITLE
PushNotification: Make 'devices' field optional

### PR DESCRIPTION
**Pull request by vanyasem**
Fixes https://github.com/famedly/matrix-dart-sdk/issues/1947

### CODE REVIEW

**Review by krille-chan — CHANGES_REQUESTED** [review]
According to  https://spec.matrix.org/v1.12/push-gateway-api/#post_matrixpushv1notify this is wrong. The devices field is required

**Comment by vanyasem** [comment]
Btw the correct documentation to link would be https://github.com/matrix-org/sygnal/blob/main/docs/applications.md#firebase-cloud-messaging, which specifies the client-side model for the push:

```json
{
  "event_id": "$3957tyerfgewrf384",
  "type": "m.room.message",
  "sender": "@exampleuser:example.org",
  "room_name": "Mission Control",
  "room_alias": "#exampleroom:example.org",
  "sender_display_name": "Major Tom",
  "content_msgtype": "m.text",
  "content_body": "I'm floating in a most peculiar way.",
  "room_id": "!slw48wfj34rtnrf:example.org",
  "prio": "high",
  "unread": "2",
  "missed_calls": "1"
}
```

**Comment by krille-chan** [comment]
@vanyasem Sygnal is just one push gateway from multiple possible gateways. The format of the data you receive from it is nowhere standartized but the server side model is. That's why we have implemented it here as it is also supported by [Hedwig](https://github.com/famedly/hedwig) and [FluffyGate](https://github.com/krille-chan/fluffygate). The purpose of a push gateway is to just forward the data to the app and that's why these two push gateways are doing.

Sygnal is just one possible use case and if you want to use it in your app you can just bring your own data model. I don't get what the blocker here is for you.

**Comment by vanyasem** [comment]
@krille-chan I'm not sure what part of the phrase "**reference** push gateway" you don't understand, but if you insists on doing it your own incorrect way - so be it

**Comment by krille-chan** [comment]
> @krille-chan I'm not sure what part of the phrase "**reference** push gateway" you don't understand, but if you insists on doing it your own incorrect way - so be it

Well a push gateway is highly bound to the app. That is app-specific implementation detail while this SDK provides matrix-specific things. Even with being a reference push gateway it does not mean, that this data format is an official standard.

**Pull request closed without merging**
