### PR TITLE
fix: Do not return invalid state events from database

### PR DESCRIPTION
**Pull request by PhantomRay**
Same fix from https://github.com/famedly/matrix-dart-sdk/pull/1835 has to applied to other two places.

### CODE REVIEW

**Review by td-famedly — APPROVED** [review]
LGTM

**Comment by nico-famedly** [comment]
can you amend your commit to match the conventional commit format (like the title of this PR for example)?

**Comment by PhantomRay** [comment]
commit message fixed. @nico-famedly

**Comment by nico-famedly** [comment]
Thanks!

**Pull request merged**
