### PR TITLE
fix: catch correct exception type for connection problems

### PR DESCRIPTION
**Pull request by krille-chan**

### CODE REVIEW

**Review by nico-famedly — APPROVED** [review]
Do we not need the MatrixConnectionException then? Or is that also derived from IOException?

**Comment by krille-chan** [comment]
> Do we not need the MatrixConnectionException then? Or is that also derived from IOException?

No, this is only used in other requests which I also have changed in a PR in the matrix api lite. Sync should never throw an MatrixConnectionException

**Comment by nico-famedly** [comment]
So we also don't need to depend on the newer api_lite, since it was already an IO error for this request?

**Comment by krille-chan** [comment]
> So we also don't need to depend on the newer api_lite, since it was already an IO error for this request?

Correct. It is for years already

**Review by nico-famedly — APPROVED** [review]

**Pull request merged**
